import React from 'react';
import { cgpaColor, passColor } from './shared';

const config = {
  title: 'Marks & Results',
  icon: '📊',
  description: "Vignan's Foundation for Science, Technology & Research — Internal · External · Semester Results · Subject Performance",
  filterConfig: {
    showType: true, showAcademicYear: true,
    types: [
      { value: 'external',            label: 'External Marks Report'       },
      { value: 'internal',            label: 'Internal Marks Report'       },
      { value: 'semester_summary',    label: 'Semester Result Summary'     },
      { value: 'subject_performance', label: 'Subject Performance Analysis'},
    ],
  },
  columns: [
    { key: 'rollNumber', label: 'Roll Number' },
    { key: 'name',       label: 'Student Name' },
    { key: 'department', label: 'Dept'         },
    { key: 'section',    label: 'Sec'          },
    { key: 'batch',      label: 'Batch'        },
    { key: 'cgpa',       label: 'CGPA',
      render: r => <span style={{ color: cgpaColor(r.cgpa), fontWeight: 700, background: cgpaColor(r.cgpa) + '15', padding: '2px 8px', borderRadius: 6 }}>{r.cgpa}</span>,
    },
    { key: 'semesters',  label: 'Sems Recorded',
      render: r => <span style={{ color: '#2563eb', fontWeight: 600 }}>{r.semesters?.length || 0}</span>,
    },
  ],
  columnSets: {
    internal: [
      { key: 'rollNumber', label: 'Roll Number' },
      { key: 'name',       label: 'Student Name' },
      { key: 'department', label: 'Dept'         },
      { key: 'section',    label: 'Sec'          },
      { key: 'batch',      label: 'Batch'        },
      { key: 'cgpa',       label: 'CGPA',
        render: r => <span style={{ color: cgpaColor(r.cgpa), fontWeight: 700, background: cgpaColor(r.cgpa) + '15', padding: '2px 8px', borderRadius: 6 }}>{r.cgpa}</span>,
      },
      { key: 'semesters',  label: 'Sems Recorded',
        render: r => <span style={{ color: '#2563eb', fontWeight: 600 }}>{r.semesters?.length || 0}</span>,
      },
    ],
    external: [
      { key: 'rollNumber', label: 'Roll Number' },
      { key: 'name',       label: 'Student Name' },
      { key: 'department', label: 'Dept'         },
      { key: 'section',    label: 'Sec'          },
      { key: 'batch',      label: 'Batch'        },
      { key: 'cgpa',       label: 'CGPA',
        render: r => <span style={{ color: cgpaColor(r.cgpa), fontWeight: 700, background: cgpaColor(r.cgpa) + '15', padding: '2px 8px', borderRadius: 6 }}>{r.cgpa}</span>,
      },
      { key: 'semesters',  label: 'Sems Recorded',
        render: r => <span style={{ color: '#2563eb', fontWeight: 600 }}>{r.semesters?.length || 0}</span>,
      },
    ],
    semester_summary: [
      { key: 'semester',      label: 'Semester',
        render: r => <span style={{ color: '#4f46e5', fontWeight: 800, fontFamily: "'Sora',sans-serif" }}>Sem {r.semester}</span>,
      },
      { key: 'academicYear',  label: 'Academic Year' },
      { key: 'totalStudents', label: 'Total',
        render: r => <span style={{ color: '#1e2d4a', fontWeight: 700 }}>{r.totalStudents}</span>,
      },
      { key: 'pass',          label: 'Pass ✅',
        render: r => <span style={{ color: '#10b981', fontWeight: 700, background: '#f0fdf4', padding: '2px 8px', borderRadius: 6 }}>{r.pass}</span>,
      },
      { key: 'fail',          label: 'Fail ❌',
        render: r => <span style={{ color: '#ef4444', fontWeight: 700, background: '#fff1f2', padding: '2px 8px', borderRadius: 6 }}>{r.fail}</span>,
      },
      { key: 'detained',      label: 'Detained',
        render: r => <span style={{ color: '#f97316', fontWeight: 700 }}>{r.detained || 0}</span>,
      },
      { key: 'avgSgpa',       label: 'Avg SGPA',
        render: r => <span style={{ color: cgpaColor(r.avgSgpa), fontWeight: 700, background: cgpaColor(r.avgSgpa) + '15', padding: '2px 8px', borderRadius: 6 }}>{r.avgSgpa}</span>,
      },
      { key: 'passPercent',   label: 'Pass %',
        render: r => <span style={{ color: passColor(r.passPercent), fontWeight: 700 }}>{r.passPercent}%</span>,
      },
    ],
    subject_performance: [
      { key: 'subjectCode',  label: 'Subject Code' },
      { key: 'subjectName',  label: 'Subject Name' },
      { key: 'semester',     label: 'Sem'          },
      { key: 'avgTotal',     label: 'Avg Total',
        render: r => <span style={{ color: '#2563eb', fontWeight: 700 }}>{r.avgTotal}</span>,
      },
      { key: 'passCount',    label: 'Pass',
        render: r => <span style={{ color: '#10b981', fontWeight: 700, background: '#f0fdf4', padding: '2px 6px', borderRadius: 5 }}>{r.passCount}</span>,
      },
      { key: 'failCount',    label: 'Fail',
        render: r => <span style={{ color: '#ef4444', fontWeight: 700, background: '#fff1f2', padding: '2px 6px', borderRadius: 5 }}>{r.failCount}</span>,
      },
      { key: 'passRate',     label: 'Pass Rate',
        render: r => <span style={{ color: passColor(r.passRate), fontWeight: 700 }}>{r.passRate}%</span>,
      },
    ],
  },
};

export default config;
